name: UhCore
version: '${project.version}'
main: io.github.nichxlas98.uhcore.UhCore
api-version: 1.19
description: Ultra Hardcore Core
commands:
  createspawn:
    description: Sets the server spawn location.
    usage: /<command>
    aliases: [setspawn, cspawn, cs]
  gotospawn:
    description: Teleports the player to spawn.
    usage: /<command>
  createborder:
    description: Creates a server border.
    usage: /<command> [size]
    aliases: [cborder, cb, setborder]
  game:
    description: Start or End the game.
    usage: /<command> <start/end>
  settings:
    description: Opens up the settings menu.
    usage: /<command>
  kits:
    description: Opens up the kits menu.
    usage: /<command>
