name: UhCore
version: '${project.version}'
main: io.github.nichxlas98.uhcore.UhCore
api-version: 1.19
description: Ultra Hardcore Core
commands:
  motd:
    description: Manage the UhCoreMC MOTD.
    usage: /<command> <toggle>
  scoreboard:
    description: Manage the UhCoreMC Scoreboard.
    usage: /<command> <toggle>
    aliases:
      - sb
  rank:
    description: Grants a player with a rank.
    usage: /<command> <player> <supporter-true/supporter-false>
  near:
    description: Displays all nearby players (supporter only)
    usage: /<command>
  a:
    description: Admin Super Commands.
    usage: /<command> <gmc/gms/spec> | <heal/feed> [player] | <broadcast> <message>
    aliases: [admin]
  feed:
    description: Feeds the player specified.
    usage: /<command> [player]
  heal:
    description: Heals the player specified.
    usage: /<command> [player]
  maintenance:
    description: Server Maintenance Mode.
    usage: /<command> <true/false>
  gethere:
    description: Teleport a player to you!
    usage: /<command> <player>
  goto:
    description: Teleport directly to a player!
    usage: /<command> <player>
  slap:
    description: Slaps a player into the air!
    usage: /<command> <player>
  pm:
    description: Private Message a player.
    usage: /<command> <player>
  createspawn:
    description: Sets the server spawn location.
    usage: /<command>
    aliases: [setspawn, cspawn, cs]
  gotospawn:
    description: Teleports the player to spawn.
    usage: /<command>
  game:
    description: Start or End the game.
    usage: /<command> <start/end>
    permission: UhCore.gameStarter
  modifiers:
    description: Opens up the modifier menu.
    usage: /<command>
  kits:
    description: Opens up the kits menu.
    usage: /<command>
  grant:
    description: Grants an Admin Level.
    usage: /<command> <player> <adminLevel>
    permission: UhCore.manager
  blockpm:
    description: Blocks the player's private messages.
    usage: /<command>

permissions:
  UhCore.manager:
    default: op
    description: Management Permissions.
  UhCore.gameStarter:
    default: op
    description: Permission to start games without being an admin.
