package io.github.nichxlas98.uhcore.commands;

import io.github.nichxlas98.uhcore.utils.AdminLevelUtil;
import org.bukkit.Bukkit;
import org.bukkit.GameMode;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.potion.PotionEffect;
import org.bukkit.potion.PotionEffectType;

import static org.bukkit.ChatColor.*;

public class aCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {

        if (sender instanceof Player) {
            Player player = (Player) sender;
            int adminLevel = AdminLevelUtil.getAdminLevel(player.getUniqueId());
            String error = RED + "[*] You do not have permission to do this!";
            if (adminLevel > 0) {
                if (args.length == 0) {
                    player.sendMessage(RED + "[*] You need to use: /a <gmc/gms/spec> | <heal/feed> (player)");
                    return true;
                }
                switch (args[0].toLowerCase()) {
                    case "heal":
                        if (adminLevel >= 2) {
                            if (args.length == 1) {
                                // Heal the sender.
                                if (player.getHealth() >= 20.0) {
                                    player.sendMessage(RED + "[*] Your health has already been regenerated.");
                                } else {
                                    player.setHealth(20.0);
                                    player.sendMessage(GREEN + "[*] Your health has been regenerated.");
                                }
                                return true;
                            }

                            Player target = Bukkit.getServer().getPlayer(args[1]);
                            if (target == null) {
                                // Target's not found.
                                player.sendMessage(RED + "[*] That player could not be found.");
                                return true;
                            }

                            if (target.getHealth() <= 19.0) {
                                target.setHealth(20.0);
                                target.sendMessage(GREEN + "[*] You've been healed by " + GOLD + player.getName() + GREEN + "!");
                                player.sendMessage(GREEN + "[*] " + GOLD + target.getName() + GREEN + " has been healed!");
                            }
                        } else {
                            player.sendMessage(error);
                        }
                        break;
                    case "feed":
                        if (adminLevel >= 2) {
                            if (args.length == 1) {
                                if (player.getFoodLevel() >= 20) {
                                    player.sendMessage(RED + "[*] Your hunger has already been regenerated.");
                                } else {
                                    player.addPotionEffect(new PotionEffect(PotionEffectType.SATURATION, 40, 100));
                                    player.setFoodLevel(20);
                                    player.sendMessage(GREEN + "[*] Your hunger has been regenerated.");
                                }
                                return true;
                            }

                            Player target = Bukkit.getServer().getPlayer(args[1]);
                            if (target == null) {
                                player.sendMessage(RED + "[*] That player could not be found.");
                                return true;
                            }

                            if (target.getFoodLevel() >= 20) {
                                player.sendMessage(RED + "[*] That player already regenerated their hunger.");
                                return true;
                            } else {
                                target.setFoodLevel(20);
                                target.sendMessage(GREEN + "[*] Your hunger has been regenerated by " + GOLD + player.getName() + GREEN + "!");
                                player.sendMessage(GREEN + "[*] " + GOLD + target.getName() + GREEN + "'s hunger has been regenerated!");
                            }

                        } else {
                            player.sendMessage(error);
                        }
                        break;
                    case "gmc":
                        if (adminLevel > 2) {
                            player.setGameMode(GameMode.CREATIVE);
                            player.sendMessage(GOLD + "[*] Your gamemode has been altered. " + RED + "(CREATIVE)");
                        } else {
                            player.sendMessage(error);
                        }
                        break;
                    case "gms":
                        if (adminLevel > 2) {
                            player.setGameMode(GameMode.SURVIVAL);
                            player.sendMessage(GOLD + "[*] Your gamemode has been altered. " + RED + "(SURVIVAL)");
                        } else {
                            player.sendMessage(error);
                        }
                        break;
                    case "spec":
                        player.setGameMode(GameMode.SPECTATOR);
                        player.sendMessage(GOLD + "[*] Your gamemode has been altered. " + RED + "(SPECTATOR)");
                        break;
                    case "broadcast":
                        String sm = "";
                        for (int i = 1; i < args.length; i++){
                            String arg = (args[i] + " ");
                            sm = (sm + arg);
                        } for (Player online : Bukkit.getOnlinePlayers()) {
                            online.sendMessage(GRAY + "[" + GOLD + "UhCore98" + GRAY + "] " + RED + sm);
                        }
                        break;
                    default:
                        player.sendMessage(RED + "[*] You need to use: /a <gmc/gms/spec> | <heal/feed> (player)");
                }
            } else {
                player.sendMessage(error);
            }
        }
        return true;
    }
}
