package io.github.nichxlas98.uhcore.commands;

import io.github.nichxlas98.uhcore.utils.AdminLevelUtil;
import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.potion.PotionEffect;
import org.bukkit.potion.PotionEffectType;

public class feedCommand implements CommandExecutor {

    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {

        if (sender instanceof Player) {
            Player player = (Player) sender;
            if (AdminLevelUtil.getAdminLevel(player.getUniqueId()) >= 2) {
                if (args.length == 0) {
                    if (player.getFoodLevel() >= 20) {
                        player.sendMessage(ChatColor.RED + "[*] Your hunger has already been regenerated.");
                    } else {
                        player.addPotionEffect(new PotionEffect(PotionEffectType.SATURATION, 40, 100));
                        player.setFoodLevel(20);
                        player.sendMessage(ChatColor.GREEN + "[*] Your hunger has been regenerated.");
                    }
                    return true;
                }

                Player target = Bukkit.getServer().getPlayer(args[0]);
                if (target == null) {
                    player.sendMessage(ChatColor.RED + "[*] That player could not be found.");
                    return true;
                }

                if (target.getFoodLevel() >= 20) {
                    player.sendMessage(ChatColor.RED + "[*] That player already regenerated their hunger.");
                    return true;
                } else {
                    target.setFoodLevel(20);
                    target.sendMessage(ChatColor.GREEN + "[*] Your hunger has been regenerated by " + ChatColor.GOLD + player.getName() + ChatColor.GREEN + "!");
                    player.sendMessage(ChatColor.GREEN + "[*] " + ChatColor.GOLD + target.getName() + ChatColor.GREEN + "'s hunger has been regenerated!");
                }

            } else {
                player.sendMessage(ChatColor.RED + "[*] You do not have permission to do this!");
            }
        } else {
            System.out.println(ChatColor.RED + "[*] You cannot do this from the console.");
        }

        return true;
    }
}
