package io.github.nichxlas98.uhcore.commands;

import org.bukkit.Bukkit;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.potion.PotionEffect;
import org.bukkit.potion.PotionEffectType;

import static io.github.nichxlas98.uhcore.models.MessageModels.*;
import static io.github.nichxlas98.uhcore.models.ModelsClass.playerAdminLevel;
import static io.github.nichxlas98.uhcore.utils.AdminlevelUtil.LOW_ADMIN_LEVEL;
import static org.bukkit.ChatColor.*;
import static org.bukkit.ChatColor.GREEN;

public class FeedCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        if (senderConsoleError(sender)) return true;
        Player player = (Player) sender;

        if (!(playerAdminLevel(player) >= LOW_ADMIN_LEVEL)) {
            player.sendMessage(PERMS_ERROR);
            return true;
        }

        if (args.length == 0) {
            if (player.getFoodLevel() >= 20) {
                player.sendMessage(RED + "[*] Your hunger has already been regenerated.");
            } else {
                player.addPotionEffect(new PotionEffect(PotionEffectType.SATURATION, 40, 100));
                player.setFoodLevel(20);
                player.sendMessage(GREEN + "[*] Your hunger has been regenerated.");
            }
            return true;
        }

        Player target = Bukkit.getServer().getPlayer(args[0]);
        if (target == null) {
            player.sendMessage(RED + "[*] That player could not be found.");
            return true;
        }

        if (target.getFoodLevel() >= 20) {
            player.sendMessage(RED + "[*] That player already regenerated their hunger.");
            return true;
        } else {
            target.setFoodLevel(20);
            target.sendMessage(GREEN + "[*] Your hunger has been regenerated by " + GOLD + player.getName() + GREEN + "!");
            player.sendMessage(GREEN + "[*] " + GOLD + target.getName() + GREEN + "'s hunger has been regenerated!");
        }
        return true;
    }
}
